name: Production

on:
  push:
    branches:
      - dev
      - main
jobs:
  prepare:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: [self-hosted]
    needs: prepare
    steps:
      - name: Building the image
        run: docker-compose build

  start:
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Running the container
        run: docker-compose up -d --remove-orphans

  clear:
    runs-on: [self-hosted]
    needs: start
    steps:
      - name: Removing old image
        run: docker image prune -f

